import { auth } from './firebase.js';
import { createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, deleteUser, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.6.0/firebase-auth.js';

const API_BASE_URL = 'https://indo-backend-production-41b1.up.railway.app';
const app = document.querySelector('#app');
let authMode = 'login';
let userIdCheckTimer;
const cleanUserId = value => value.trim().toLowerCase().replace(/^@/, '');
const validUserId = value => value.length >= 1 && value.length <= 50;
const firebaseMessage = error => ({'auth/email-already-in-use':'This email is already registered.','auth/invalid-email':'Enter a valid email address.','auth/weak-password':'Password must be at least 6 characters.','auth/invalid-credential':'Email or password is incorrect.','auth/too-many-requests':'Too many attempts. Try again later.'}[error.code] || error.message || 'Something went wrong.');

function renderAuth(error='', success='', values={}) {
 const signup=authMode==='signup';
 app.innerHTML=`<main class="auth-page"><section class="auth-card"><div class="brand">Indo</div><h1>${signup?'Create your account':'Welcome back'}</h1><p class="muted">${signup?'Create your real Indo account.':'Login with your Indo account.'}</p>${error?`<div class="error">${error}</div>`:''}${success?`<div class="success">${success}</div>`:''}${signup?`<div class="field"><label>User name</label><input id="name" maxlength="60" value="${values.name||''}" placeholder="Your name" autocomplete="name"></div><div class="field"><label>User ID</label><div class="prefix-wrap"><span>@</span><input id="username" maxlength="50" value="${values.username||''}" placeholder="Choose any User ID" autocomplete="username"><span id="userIdStatus" class="muted small"></span></div><div class="muted small">Type any User ID. We'll check availability as you type.</div></div>`:''}<div class="field"><label>Email</label><input id="email" type="email" value="${values.email||''}" placeholder="you@example.com" autocomplete="email"></div><div class="field"><label>Password</label><input id="password" type="password" placeholder="Minimum 6 characters" autocomplete="current-password"></div>${signup?`<div class="field"><label>Confirm password</label><input id="confirm" type="password" placeholder="Repeat password" autocomplete="new-password"></div><div class="field"><label>Account type</label><div class="choice-row"><label class="choice"><input type="radio" name="privacy" value="public" checked> Public</label><label class="choice"><input type="radio" name="privacy" value="private"> Private</label></div></div>`:''}<button id="submit" class="primary">${signup?'Create Account':'Login'}</button><button id="switch" class="link">${signup?'Already have an account? Login':'New to Indo? Create Account'}</button></section></main>`;
 document.querySelector('#switch').onclick=()=>{authMode=signup?'login':'signup';renderAuth();};
 document.querySelector('#submit').onclick=signup?createAccount:login;
 if(signup) document.querySelector('#username').addEventListener('input', liveUserIdCheck);
}
async function liveUserIdCheck(event){const input=event.target,status=document.querySelector('#userIdStatus'),username=cleanUserId(input.value);clearTimeout(userIdCheckTimer);if(!username){status.textContent='';return;}if(!validUserId(username)){status.textContent='';return;}status.textContent='Checking...';userIdCheckTimer=setTimeout(async()=>{try{const response=await fetch(`${API_BASE_URL}/api/account/check-user-id`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:username})});const data=await response.json();status.textContent=data.ok?(data.available?'Available':'Already exists'):(data.error||'Could not check');}catch{status.textContent='Could not check';}},350);}
async function createAccount(){const button=document.querySelector('#submit'),name=document.querySelector('#name').value.trim(),username=cleanUserId(document.querySelector('#username').value),email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value,confirm=document.querySelector('#confirm').value,privacy=document.querySelector('input[name="privacy"]:checked').value,values={name,username,email};if(!name)return renderAuth('Please enter your User name.','',values);if(!validUserId(username))return renderAuth('Please enter your User ID.','',values);if(!email)return renderAuth('Please enter your email.','',values);if(password.length<6)return renderAuth('Password must be at least 6 characters.','',values);if(password!==confirm)return renderAuth('Passwords do not match.','',values);button.disabled=true;button.textContent='Creating...';let createdUser=null;try{const availability=await fetch(`${API_BASE_URL}/api/account/check-user-id`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:username})}),availabilityData=await availability.json();if(!availabilityData.ok)throw new Error(availabilityData.error||'Could not verify User ID.');if(!availabilityData.available){renderAuth(`@${username} is already taken. Choose another User ID.`,'',values);return;}const credential=await createUserWithEmailAndPassword(auth,email,password);createdUser=credential.user;const token=await createdUser.getIdToken(true);const response=await fetch(`${API_BASE_URL}/api/account/claim-user-id`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({userId:username,name,accountType:privacy})});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||'Could not finish account creation.');await signOut(auth);authMode='login';renderAuth('',`Account created. Your Indo ID is ${data.indoId}. Please login.`);}catch(error){try{if(createdUser&&auth.currentUser?.uid===createdUser.uid)await deleteUser(createdUser);}catch{}try{if(auth.currentUser)await signOut(auth);}catch{}renderAuth(error.message||firebaseMessage(error),'',values);}}
async function login(){const button=document.querySelector('#submit'),email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value;if(!email||!password)return renderAuth('Enter your email and password.');button.disabled=true;button.textContent='Logging in...';try{await signInWithEmailAndPassword(auth,email,password);}catch(error){renderAuth(firebaseMessage(error));}}

function showHome(user){
 app.innerHTML=`<main class="home-page"><header class="topbar home-topbar"><div class="indo-logo">Indo</div><div class="home-actions"><button class="icon-btn plus-btn" aria-label="Create" title="Create">＋</button><button class="icon-btn" aria-label="Search" title="Search">⌕</button><button class="icon-btn" aria-label="Notifications" title="Notifications">♢</button></div></header><section class="home-content"><div class="stories-title">Stories</div><div class="stories-row"><button class="story own-story"><span class="story-ring"><span class="story-avatar">+</span></span><small>Your Story</small></button><button class="story"><span class="story-ring"><span class="story-avatar">A</span></span><small>@alex</small></button><button class="story"><span class="story-ring"><span class="story-avatar">R</span></span><small>@ravi</small></button><button class="story"><span class="story-ring"><span class="story-avatar">S</span></span><small>@sneha</small></button><button class="story"><span class="story-ring"><span class="story-avatar">K</span></span><small>@kiran</small></button></div><div class="feed-label">Latest</div><div class="feed-list"><article class="feed-card social-card"><div class="feed-head"><div class="mini-avatar">A</div><div><strong>@alex</strong><small>Recently uploaded</small></div><button class="icon-btn">•••</button></div><div class="media-placeholder reel-preview"><span>REEL</span></div><div class="feed-actions"><button>♡ <small>Share</small></button><button>♡ <small>Like</small></button><button>◉ <small>Views</small></button><button>◌ <small>Comment</small></button><button>▱ <small>Save</small></button></div></article><article class="feed-card social-card"><div class="feed-head"><div class="mini-avatar">R</div><div><strong>@ravi</strong><small>Recently uploaded</small></div><button class="icon-btn">•••</button></div><div class="media-placeholder post-preview"><span>POST</span></div><div class="feed-actions"><button>♡ <small>Share</small></button><button>♡ <small>Like</small></button><button>◉ <small>Views</small></button><button>◌ <small>Comment</small></button><button>▱ <small>Save</small></button></div></article></div></section><nav class="bottom-nav home-nav"><button class="nav-btn active">⌂<span>Home</span></button><button class="nav-btn">✉<span>Messages</span></button><button class="nav-btn">▶<span>Reels</span></button><button class="nav-btn">▣<span>Videos</span></button><button class="nav-btn">◎<span>Profile</span></button></nav><div id="createSheet" class="create-sheet hidden"><div class="create-panel"><button class="close-create">×</button><h3>Create</h3><button class="create-option">＋ Post</button><button class="create-option">▶ Reel</button><button class="create-option disabled">▣ Video <small>Public account only</small></button></div></div></main>`;
 document.querySelector('.plus-btn').onclick=()=>document.querySelector('#createSheet').classList.remove('hidden');
 document.querySelector('.close-create').onclick=()=>document.querySelector('#createSheet').classList.add('hidden');
 document.querySelectorAll('.nav-btn').forEach((button,index)=>button.onclick=()=>{if(index===4)showProfile(user);});
}
function showProfile(user){app.innerHTML=`<main class="profile-page"><header class="topbar"><div class="indo-logo">Indo</div><button id="backHome" class="icon-btn">←</button></header><section class="profile-card profile-view"><div class="profile-avatar">${(user.email?.[0]||'U').toUpperCase()}</div><h2>${user.displayName||user.email?.split('@')[0]||'User'}</h2><p class="muted">${user.email}</p><div class="profile-stats"><div><strong>0</strong><span>Posts</span></div><div><strong>0</strong><span>Followers</span></div><div><strong>0</strong><span>Following</span></div></div><button id="logout" class="primary">Logout</button></section></main>`;document.querySelector('#backHome').onclick=()=>showHome(user);document.querySelector('#logout').onclick=async()=>{await signOut(auth);authMode='login';renderAuth();};}

onAuthStateChanged(auth,user=>user?showHome(user):renderAuth());
