const STORAGE_PREFIX='indo:recommendation:v2:';
const STOP_WORDS=new Set(['the','and','for','with','from','this','that','your','you','are','was','has','have','into','about','video','videos','reel','reels','indo','user','new','latest','more','than','just','here','what','when','where','will','their','they','then','also','only','very']);
const MAX_TOKENS=260;
const MAX_MEDIA_HISTORY=500;
const DAY_MS=24*60*60*1000;
function currentUserId(){return String(window.__indoRecommendationUid||'guest').trim()||'guest'}
function storageKey(){return `${STORAGE_PREFIX}${currentUserId()}`}
function tokenise(value=''){return [...new Set(String(value).toLowerCase().replace(/https?:\/\/\S+/g,' ').replace(/[@#]/g,' ').split(/[^a-z0-9]+/).filter(token=>token.length>=3&&!STOP_WORDS.has(token)))]}
function loadProfile(){try{const raw=localStorage.getItem(storageKey());const parsed=raw?JSON.parse(raw):{};return parsed&&typeof parsed==='object'?parsed:{tokens:{},creators:{},searches:{},media:{}}}catch{return{tokens:{},creators:{},searches:{},media:{}}}}
function saveProfile(profile){try{const clean={tokens:profile.tokens||{},creators:profile.creators||{},searches:profile.searches||{},media:profile.media||{}};clean.tokens=Object.fromEntries(Object.entries(clean.tokens).sort((a,b)=>Number(b[1]?.weight||0)-Number(a[1]?.weight||0)).slice(0,MAX_TOKENS));clean.media=Object.fromEntries(Object.entries(clean.media).sort((a,b)=>Number(b[1]?.last||0)-Number(a[1]?.last||0)).slice(0,MAX_MEDIA_HISTORY));localStorage.setItem(storageKey(),JSON.stringify(clean))}catch{}}
function addWeightedTokens(profile,tokens,weight){const now=Date.now();for(const token of tokens){const current=profile.tokens[token]||{weight:0,last:now};const age=Math.max(0,now-Number(current.last||now));const decay=Math.pow(0.5,age/(7*DAY_MS));current.weight=Number(current.weight||0)*decay+weight;current.last=now;profile.tokens[token]=current}}
function mediaText(media={}){return[media.title,media.caption,media.creator,media.creatorName,media.userId,media.username,media.category,media.tags].flatMap(value=>Array.isArray(value)?value:[value]).filter(Boolean).join(' ')}
export function recordInterestText(text,weight=1,meta={}){const profile=loadProfile();addWeightedTokens(profile,tokenise(text),weight);if(meta.creator){const creator=String(meta.creator).replace(/^@/,'').toLowerCase();if(creator)profile.creators[creator]=(Number(profile.creators[creator])||0)+weight}if(meta.mediaId){const id=String(meta.mediaId);profile.media[id]={last:Date.now(),weight:(Number(profile.media[id]?.weight)||0)+weight}}saveProfile(profile)}
export function recordMediaInteraction(media,kind='view'){const weight={view:1,watch:1.4,complete:2,like:5,save:5,share:6,comment:3,follow:4,skip:-1}[kind]??1;recordInterestText(mediaText(media),weight,{mediaId:media?.id,creator:media?.creator||media?.userId||media?.username})}
export function recordSearchQuery(query){const tokens=tokenise(query);if(!tokens.length)return;const profile=loadProfile();addWeightedTokens(profile,tokens,4);for(const token of tokens)profile.searches[token]=(Number(profile.searches[token])||0)+1;saveProfile(profile)}
function relevanceScore(media,interests){const tokens=tokenise(mediaText(media));if(!tokens.length)return 0;let score=0;for(const token of tokens)score+=Number(interests[token]||0);return score/tokens.length}
function normalizedEngagement(media){const views=Math.max(0,Number(media.views||0));const likes=Math.max(0,Number(media.likes||0));const comments=Math.max(0,Number(media.comments||0));return Math.log1p(views)*0.55+Math.log1p(likes)*0.9+Math.log1p(comments)*0.8}
function recencyScore(createdAt){const age=Math.max(0,Date.now()-Number(createdAt||Date.now()));return Math.max(0,1-(age/(7*DAY_MS)))}
export function scoreMedia(media,{type='',freshness=1}={}){const profile=loadProfile();const now=Date.now();const interests={};for(const[token,item]of Object.entries(profile.tokens||{})){const age=Math.max(0,now-Number(item?.last||now));interests[token]=Number(item?.weight||0)*Math.pow(0.5,age/(14*DAY_MS))}const personal=relevanceScore(media,interests);const engagement=normalizedEngagement(media);const recent=recencyScore(media.createdAt);const creator=String(media.creator||media.userId||media.username||'').replace(/^@/,'').toLowerCase();const creatorBoost=creator&&profile.creators?.[creator]?Math.min(1,Number(profile.creators[creator])/8):0;const viewed=Number(profile.media?.[String(media.id)]?.weight||0);const viewedPenalty=viewed>0?Math.min(1.3,viewed*.1):0;const exploration=Math.random()*0.12;return personal*6+engagement*.8+recent*(2.6*freshness)+creatorBoost*2.2-viewedPenalty+exploration+(type&&String(media.mediaType||'').toLowerCase()===type?0.12:0)}
export function rankMedia(items,{type='',limit=50,freshness=1}={}){const list=Array.isArray(items)?[...items]:[];return list.sort((a,b)=>scoreMedia(b,{type,freshness})-scoreMedia(a,{type,freshness})).slice(0,Math.max(0,limit))}
function getUrl(input){try{return input instanceof Request?input.url:String(input||'')}catch{return String(input||'')}}
function withType(url,type){const parsed=new URL(url,window.location.origin);parsed.searchParams.set('type',type);return parsed.toString()}
function withLimit(url,limit){const parsed=new URL(url,window.location.origin);parsed.searchParams.set('limit',String(limit));return parsed.toString()}
function cloneInit(init){return init?{...init,headers:init.headers?{...init.headers}:init.headers}:undefined}
export function installRecommendationFetch(){if(window.__indoRecommendationFetchInstalled)return;window.__indoRecommendationFetchInstalled=true;const original=window.fetch.bind(window);window.__indoOriginalFetch=original;window.fetch=async(input,init={})=>{const url=getUrl(input);if(!/\/api\/media\/videos(?:\?|$)/.test(url))return original(input,init);let parsed;try{parsed=new URL(url,window.location.origin)}catch{return original(input,init)}const type=String(parsed.searchParams.get('type')||'').toLowerCase();const limit=Math.min(100,Math.max(1,Number(parsed.searchParams.get('limit')||50)));const screen=String(window.__indoRecommendationScreen||'');if(screen==='home'&&type==='video'){const vUrl=withLimit(withType(url,'video'),Math.max(limit,50));const rUrl=withLimit(withType(url,'reel'),Math.max(limit,50));const [vr,rr]=await Promise.all([original(vUrl,cloneInit(init)),original(rUrl,cloneInit(init))]);const [vd,rd]=await Promise.all([vr.json().catch(()=>({})),rr.json().catch(()=>({}))]);const merged=[...(Array.isArray(vd.videos)?vd.videos:[]),...(Array.isArray(rd.videos)?rd.videos:[])];return new Response(JSON.stringify({ok:true,videos:rankMedia(merged,{limit})}),{status:200,headers:{'Content-Type':'application/json'}})}if(type==='video'||type==='reel'){const response=await original(input,init);if(!response.ok)return response;const data=await response.json().catch(()=>({}));return new Response(JSON.stringify({...data,videos:rankMedia(Array.isArray(data.videos)?data.videos:[],{type,limit,freshness:screen==='video'||screen==='reels'?1.15:1})}),{status:response.status,statusText:response.statusText,headers:{'Content-Type':'application/json'}})}return original(input,init)}}
function mediaFromNode(node){if(!node)return null;const container=node.closest?.('[data-video-id],.video-post,.reel-view,.indo-video-card,.indo-video-mini');if(!container)return null;const id=String(container.dataset?.videoId||container.dataset?.videoOpen||'').trim();const text=container.textContent||'';return{id,title:text.slice(0,180),caption:text,creator:container.querySelector?.('.neon-edge-name,.indo-video-user-id,.reel-user b,.indo-video-mini-name')?.textContent||'',mediaType:container.classList.contains('reel-view')?'reel':'video'}}
export function installRecommendationTracking(){if(window.__indoRecommendationTrackingInstalled)return;window.__indoRecommendationTrackingInstalled=true;document.addEventListener('input',event=>{const target=event.target;if(!(target instanceof HTMLInputElement))return;const placeholder=String(target.placeholder||'').toLowerCase();if(!placeholder.includes('search'))return;clearTimeout(target.__indoSearchTimer);target.__indoSearchTimer=setTimeout(()=>recordSearchQuery(target.value||''),500)},true);document.addEventListener('click',event=>{const element=event.target instanceof Element?event.target:null;if(!element)return;const engagement=element.closest('[data-engagement]');if(engagement){const media=mediaFromNode(engagement);if(media)recordMediaInteraction(media,String(engagement.dataset.engagement||'view'));return}const videoOpen=element.closest('[data-video-open]');if(videoOpen){const media=mediaFromNode(videoOpen);if(media)recordMediaInteraction(media,'view');return}const follow=element.closest('[data-follow-uid]');if(follow){const media=mediaFromNode(follow);if(media)recordMediaInteraction(media,'follow')}},true);document.addEventListener('play',event=>{const video=event.target;if(!(video instanceof HTMLVideoElement))return;const media=mediaFromNode(video);if(media)recordMediaInteraction(media,'view')},true);document.addEventListener('timeupdate',event=>{const video=event.target;if(!(video instanceof HTMLVideoElement))return;const now=Date.now();if(now-Number(video.__indoLastRecommendationTick||0)<10000)return;video.__indoLastRecommendationTick=now;const media=mediaFromNode(video);if(media)recordMediaInteraction(media,'watch')},true);document.addEventListener('ended',event=>{const video=event.target;if(!(video instanceof HTMLVideoElement))return;const media=mediaFromNode(video);if(media)recordMediaInteraction(media,'complete')},true)}
export function initRecommendationEngine(){installRecommendationFetch();installRecommendationTracking()}
