import { bindAuthSwitches, bindLoginForm, bindSignupForm } from './features/auth/auth-controller.js';
const app=document.getElementById('root');let busy=false;let started=false;
async function installLiveAvatars(){try{await import('./features/profile/profile-avatar-live.js?v=20260815-avatar-v5')}catch(error){console.warn('Live profile avatars unavailable:',error)}}
async function render(){const{state}=await import('./state.js');const{render}=await import('./router.js');await render(app);await installLiveAvatars();bindAuthSwitches();bindLoginForm();bindSignupForm()}
async function navigate(screen){if(busy)return;busy=true;try{const{state}=await import('./state.js');if(screen==='profile')state.profile=null;state.screen=String(screen||'home');await render();window.scrollTo({top:0,behavior:'auto'})}finally{busy=false}}
if(!window.__indoUniversalNavigation){window.__indoUniversalNavigation=true;document.addEventListener('click',event=>{const el=event.target instanceof Element?event.target:null;const button=el?.closest('[data-screen]');if(!button)return;const screen=button.getAttribute('data-screen');if(!screen)return;event.preventDefault();event.stopImmediatePropagation();if(screen==='profile'&&button.hasAttribute('data-own-profile')){import('./state.js').then(({state})=>{state.profile=null;state.screen='profile';return render()}).then(()=>window.scrollTo({top:0,behavior:'auto'})).catch(console.error);return}navigate(screen).catch(console.error)},true)}
function showBootFailure(message='Could not start Indo. Please reload the app.'){if(!app)return;app.innerHTML=`<main class="splash-screen splash-error"><div class="splash-name">Indo</div><p>${message}</p><button type="button" id="indo-retry-boot" style="margin-top:14px;padding:10px 16px;border-radius:10px;background:#743cff;color:#fff;font-weight:800;cursor:pointer">Retry</button></main>`;document.getElementById('indo-retry-boot')?.addEventListener('click',()=>window.location.reload())}
async function start(){if(started)return;started=true;try{const{auth}=await import('./features/auth/firebase-client.js?v=20260815-auth-v3');const{onAuthStateChanged}=await import('https://www.gstatic.com/firebasejs/12.6.0/firebase-auth.js');let settled=false;const bootWithUser=async user=>{if(settled)return;settled=true;const{state}=await import('./state.js');state.authenticated=Boolean(user);if(user&&(state.screen==='auth-login'||state.screen==='auth-signup'))state.screen='home';if(!user&&!String(state.screen||'').startsWith('auth-'))state.screen='auth-login';try{await Promise.race([render(),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Startup timed out.')),10000))])}catch(error){console.error('Indo startup failed:',error);showBootFailure()}};let unsubscribe;const firstAuth=new Promise(resolve=>{unsubscribe=onAuthStateChanged(auth,user=>resolve(user),()=>resolve(auth.currentUser||null))});const user=await Promise.race([firstAuth,new Promise(resolve=>setTimeout(()=>resolve(auth.currentUser||null),8000))]);try{unsubscribe?.()}catch{}await bootWithUser(user||null)}catch(error){console.error('Indo boot failed:',error);showBootFailure('Indo could not start.')}}
window.__indoNavigate=navigate;start();
