import { bindAuthSwitches, bindLoginForm, bindSignupForm } from './features/auth/auth-controller.js?v=227';
const app=document.getElementById('root');const ROUTER_VERSION='227';const SPLASH_MS=2500;let navigationBusy=false;let splashStartedAt=Date.now();
async function navigate(screen){const target=String(screen||'').trim();if(!target||navigationBusy)return;navigationBusy=true;try{const {state}=await import('./state.js');if(state.screen===target)return;state.screen=target;window.__indoRecommendationScreen=target;await render();window.scrollTo({top:0,behavior:'auto'})}finally{navigationBusy=false}}
function installNavigationClicks(){if(window.__indoNavigationClicksInstalledV227)return;window.__indoNavigationClicksInstalledV227=true;document.addEventListener('click',(event)=>{const element=event.target instanceof Element?event.target:null;const button=element?.closest('[data-screen]');if(!button)return;const surface=button.closest('.indo-global-bottom-nav,.indo-option5-topbar,.indo-brand-topbar,.bottom-nav,.page-head,.reels-top');if(!surface)return;const screen=button.getAttribute('data-screen');if(!screen)return;event.preventDefault();event.stopPropagation();navigate(screen).catch(error=>console.error('Indo navigation failed:',error))},true)}
async function waitForSplash(){const elapsed=Date.now()-splashStartedAt;const remaining=Math.max(0,SPLASH_MS-elapsed);if(remaining)await new Promise(resolve=>setTimeout(resolve,remaining));}
async function render(){const {state}=await import('./state.js');window.__indoRecommendationScreen=String(state.screen||'home');const {render}=await import(`./router-v227.js?v=${ROUTER_VERSION}`);await render(app);bindAuthSwitches();bindLoginForm();bindSignupForm()}
function showBootError(error){console.error('Indo startup failed:',error);app.innerHTML='<main class="splash-screen splash-error"><div class="splash-name">Indo</div><p>Indo could not start.</p><small>Please reload the app.</small></main>'}
async function start(){installNavigationClicks();try{try{const mod=await import(`./features/feed/recommendation.js?v=${ROUTER_VERSION}`);if(typeof mod.initRecommendationEngine==='function')mod.initRecommendationEngine()}catch(error){console.warn('Recommendation engine disabled for this boot:',error)}const {auth}=await import('./features/auth/firebase-client.js');const {onAuthStateChanged}=await import('https://www.gstatic.com/firebasejs/12.6.0/firebase-auth.js');onAuthStateChanged(auth,async(user)=>{const {state}=await import('./state.js');state.authenticated=Boolean(user);window.__indoRecommendationUid=String(user?.uid||'guest');if(user&&(state.screen==='auth-login'||state.screen==='auth-signup'))state.screen='home';if(!user&&!String(state.screen||'').startsWith('auth-'))state.screen='auth-login';window.__indoRecommendationScreen=String(state.screen||'auth-login');try{await waitForSplash();await render()}catch(error){showBootError(error)}})}catch(error){await waitForSplash();showBootError(error)}}
window.__indoNavigate=navigate;start();
