import { state } from './state.js';
import { renderLogin, renderSignup } from './screens/auth.js';
import { nav } from './components/nav.js';
import './features/ui/feed-follow-button.js';
import { renderHomeTopbar, installHomeTopbarStyles } from './screens/home-topbar-v2.js';
const NAV_STYLE_ID='indo-universal-nav';
function fail(app,error){console.error('Indo route error:',error);app.innerHTML=`<main class="splash-screen splash-error"><div class="splash-name">Indo</div><p>Indo could not open this screen.</p><small>${String(error?.message||error||'Unable to open this screen.').replace(/[&<>\"']/g,'')}</small><button type="button" data-screen="home">Back to Home</button></main>`}
function installNavStyles(){if(document.getElementById(NAV_STYLE_ID))return;const s=document.createElement('style');s.id=NAV_STYLE_ID;s.textContent=`.indo-global-bottom-nav,.bottom-nav{position:fixed!important;left:50%!important;bottom:0!important;transform:translateX(-50%)!important;width:min(100%,520px)!important;height:68px!important;z-index:99999!important;display:grid!important;grid-template-columns:repeat(5,1fr)!important;gap:0!important;background:#0f0f14!important;border-top:1px solid #24242b!important;box-sizing:border-box!important;padding:0!important;margin:0!important}.indo-global-bottom-nav button,.bottom-nav button{border:0!important;background:transparent!important;color:#85858f!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:4px!important;padding:6px 2px!important;margin:0!important;font:700 11px/1.1 Arial,sans-serif!important;cursor:pointer!important}.indo-global-bottom-nav button.active,.bottom-nav button.active{color:#fff!important}.indo-global-bottom-nav svg,.bottom-nav svg{width:20px!important;height:20px!important}.indo-global-bottom-nav span,.bottom-nav span{display:block!important}`;document.head.appendChild(s)}
function activeNav(){if(state.screen==='messages')return'messages';if(state.screen==='reels')return'reels';if(state.screen==='video'||state.screen==='watch-video')return'video';if(['profile','settings','edit-profile'].includes(state.screen))return'profile';return'home'}
function ensureUniversalNav(app){if(!app||['auth-login','auth-signup','edit-profile','watch-video'].includes(state.screen))return;installNavStyles();app.querySelectorAll('.bottom-nav,.indo-global-bottom-nav').forEach(n=>n.remove());const wrapper=document.createElement('div');wrapper.innerHTML=nav(activeNav());const bottom=wrapper.firstElementChild;if(bottom){bottom.classList.add('indo-global-bottom-nav');app.appendChild(bottom)}}
function ensureHomeTopbar(app){if(state.screen!=='home')return;installHomeTopbarStyles();app.querySelector('.topbar')?.remove();const w=document.createElement('div');w.innerHTML=renderHomeTopbar();const node=w.firstElementChild;if(node)app.querySelector('.app-shell')?.prepend(node)}
async function lazy(app,path,name,args=[]){try{const m=await import(path);if(typeof m[name]!=='function')throw new Error(`Missing screen renderer: ${name}`);await m[name](app,...args)}catch(e){fail(app,e)}}
export async function render(app){try{switch(state.screen){case'auth-login':return renderLogin(app);case'auth-signup':return renderSignup(app);case'home':await lazy(app,'./screens/home-v2.js','renderHome');ensureHomeTopbar(app);break;case'messages':await lazy(app,'./screens/messages.js','renderMessages');break;case'reels':await lazy(app,'./screens/reels.js','renderReels');break;case'video':await lazy(app,'./screens/video.js','renderVideo');break;case'watch-video':await lazy(app,'./screens/watch-video.js','renderWatchVideo');break;case'create':await lazy(app,'./screens/create.js','renderCreate');break;case'upload-video':await lazy(app,'./screens/upload-video.js','renderUploadVideo');break;case'story-create':await lazy(app,'./screens/story-create.js','renderStoryCreate',[window.__indoStoryDraftFile instanceof File?window.__indoStoryDraftFile:null]);break;case'profile':await lazy(app,'./screens/profile.js','renderProfile',[state.profile]);break;case'edit-profile':await lazy(app,'./screens/edit-profile.js','renderEditProfile',[state.profile]);break;case'settings':await lazy(app,'./screens/settings.js','renderSettings',[state.accountType,state.earning,state.earningSummary]);break;case'search':await lazy(app,'./screens/search.js','renderSearch');break;case'notifications':await lazy(app,'./screens/notifications.js','renderNotifications');break;case'activity':await lazy(app,'./screens/notifications.js','renderNotifications',['activity']);break;case'wallet':await lazy(app,'./screens/wallet.js','renderWallet');break;case'blocked-users':await lazy(app,'./screens/blocked-users.js','renderBlockedUsers');break;default:state.screen='home';await lazy(app,'./screens/home-v2.js','renderHome');ensureHomeTopbar(app)}ensureUniversalNav(app)}catch(e){fail(app,e)}}