import { state } from './state.js';
import { renderLogin, renderSignup } from './screens/auth.js';
import './features/ui/feed-follow-button.js';

const VERSION = '20260814-147';
const NAV_STYLE_ID = 'indo-global-nav-v147';

function renderRouteError(app, error) {
  const message = String(error?.message || error || 'Unable to open this screen.').replace(/[&<>\"']/g, '');
  app.innerHTML = `<main class="splash-screen splash-error"><div class="splash-logo">I</div><div class="splash-name">Indo</div><p>Indo could not open this screen.</p><small>${message}</small><button type="button" data-screen="home">Back to Home</button></main>`;
}
function ensureGlobalNavStyle(){if(document.getElementById(NAV_STYLE_ID))return;const style=document.createElement('style');style.id=NAV_STYLE_ID;style.textContent='.indo-global-bottom-nav{position:fixed!important;left:50%!important;bottom:0!important;transform:translateX(-50%)!important;width:min(100%,520px)!important;height:68px!important;display:grid!important;grid-template-columns:repeat(5,1fr)!important;align-items:stretch!important;z-index:9000!important;background:#0f0f14!important;border-top:1px solid #24242b!important;box-sizing:border-box!important}.indo-global-bottom-nav button{appearance:none!important;border:0!important;background:transparent!important;color:#85858f!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:4px!important;padding:6px 2px!important;font:700 11px/1.1 Arial,sans-serif!important;cursor:pointer!important}.indo-global-bottom-nav button .indo-nav-icon{font-size:22px!important;line-height:1!important;font-weight:700!important}.indo-global-bottom-nav button.active{color:#fff!important}.indo-global-bottom-nav button[data-screen="video"] .indo-nav-icon{font-size:19px!important}.indo-global-bottom-nav button[data-screen="messages"] .indo-nav-icon{font-size:20px!important}';document.head.appendChild(style)}
function activeNavScreen(){if(state.screen==='messages')return'messages';if(state.screen==='video')return'video';if(state.screen==='reels')return'reels';if(state.screen==='profile'||state.screen==='settings')return'profile';return'home'}
function installGlobalBottomNav(app){if(!app||state.screen==='auth-login'||state.screen==='auth-signup')return;ensureGlobalNavStyle();app.querySelectorAll('.bottom-nav,.indo-global-bottom-nav').forEach(node=>node.remove());const active=activeNavScreen();const nav=document.createElement('nav');nav.className='indo-global-bottom-nav';nav.setAttribute('aria-label','Primary navigation');nav.innerHTML=`<button type="button" data-screen="home" class="${active==='home'?'active':''}" aria-label="Home"><span class="indo-nav-icon">⌂</span><span>Home</span></button><button type="button" data-screen="messages" class="${active==='messages'?'active':''}" aria-label="Message"><span class="indo-nav-icon">⌕</span><span>Message</span></button><button type="button" data-screen="reels" class="${active==='reels'?'active':''}" aria-label="Reel"><span class="indo-nav-icon">▶</span><span>Reel</span></button><button type="button" data-screen="video" class="${active==='video'?'active':''}" aria-label="Video"><span class="indo-nav-icon">▣</span><span>Video</span></button><button type="button" data-screen="profile" class="${active==='profile'?'active':''}" aria-label="Profile"><span class="indo-nav-icon">●</span><span>Profile</span></button>`;app.appendChild(nav)}
async function installHomeTopbar(app){if(state.screen!=='home')return;const {renderHomeTopbar,installHomeTopbarStyles}=await import(`./screens/home-topbar-v2.js?v=${VERSION}`);installHomeTopbarStyles();const existing=app.querySelector('.topbar');if(existing)existing.outerHTML=renderHomeTopbar()}
async function renderLazy(app,modulePath,exportName,args=[]){try{const module=await import(`${modulePath}?v=${VERSION}`);const renderer=module[exportName];if(typeof renderer!=='function')throw new Error(`Missing screen renderer: ${exportName}`);await renderer(app,...args)}catch(error){console.error(`Failed to load ${modulePath}:`,error);renderRouteError(app,error)}}
export function preloadAppScreens(){}
export async function render(app){switch(state.screen){case'auth-login':return renderLogin(app);case'auth-signup':return renderSignup(app);case'home':await renderLazy(app,'./screens/home-v2.js','renderHome');await installHomeTopbar(app);break;case'messages':await renderLazy(app,'./screens/messages.js','renderMessages');break;case'reels':await renderLazy(app,'./screens/reels.js','renderReels');break;case'video':await renderLazy(app,'./screens/video.js','renderVideo');break;case'create':await renderLazy(app,'./screens/create.js','renderCreate');break;case'story-create':await renderLazy(app,'./screens/story-create.js','renderStoryCreate',[window.__indoStoryDraftFile instanceof File?window.__indoStoryDraftFile:null]);break;case'profile':await renderLazy(app,'./screens/profile-direct.js','renderProfile',[state.profile]);break;case'settings':await renderLazy(app,'./screens/settings.js','renderSettings',[state.accountType,state.earning,state.earningSummary]);break;case'search':await renderLazy(app,'./screens/search.js','renderSearch');break;case'notifications':await renderLazy(app,'./screens/notifications.js','renderNotifications');break;case'activity':await renderLazy(app,'./screens/activity.js','renderActivity');break;case'wallet':await renderLazy(app,'./screens/wallet.js','renderWallet');break;case'blocked-users':await renderLazy(app,'./screens/blocked-users.js','renderBlockedUsers');break;default:state.screen='home';await renderLazy(app,'./screens/home-v2.js','renderHome');await installHomeTopbar(app);break}installGlobalBottomNav(app)}
