import { state } from './state.js';
import { renderLogin, renderSignup } from './screens/auth.js?v=245';
import './features/ui/feed-follow-button.js';
import { installProfileLinkNavigation } from './features/ui/profile-link-navigation-v236.js';
const VERSION='245'; const NAV_STYLE_ID='indo-global-nav-v245';
function routeError(app,error){console.error('Route error:',error);const message=String(error?.message||error||'Unable to open this screen.').replace(/[&<>\"']/g,'');app.innerHTML=`<main class="splash-screen splash-error"><div class="splash-logo">I</div><div class="splash-name">Indo</div><p>Indo could not open this screen.</p><small>${message}</small><button type="button" data-screen="home">Back to Home</button></main>`;}
function navStyle(){if(document.getElementById(NAV_STYLE_ID))return;const s=document.createElement('style');s.id=NAV_STYLE_ID;s.textContent='.indo-global-bottom-nav{position:fixed!important;left:50%!important;bottom:0!important;transform:translateX(-50%)!important;width:min(100%,520px)!important;height:68px!important;display:grid!important;grid-template-columns:repeat(5,1fr)!important;z-index:9000!important;background:#0f0f14!important;border-top:1px solid #24242b!important;box-sizing:border-box!important}.indo-global-bottom-nav button{border:0!important;background:transparent!important;color:#85858f!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:4px!important;padding:6px 2px!important;font:700 11px/1.1 Arial,sans-serif!important}.indo-global-bottom-nav button.active{color:#fff!important}.indo-global-bottom-nav .indo-nav-icon{font-size:22px!important;line-height:1!important}';document.head.appendChild(s);}
function activeNav(){if(state.screen==='messages')return'messages';if(state.screen==='video'||state.screen==='watch-video')return'video';if(state.screen==='reels')return'reels';if(state.screen==='profile'||state.screen==='settings'||state.screen==='edit-profile')return'profile';return'home';}
function globalNav(app){if(!app||['auth-login','auth-signup','watch-video','edit-profile'].includes(state.screen))return;navStyle();app.querySelectorAll('.bottom-nav,.indo-global-bottom-nav').forEach(n=>n.remove());const a=activeNav(),n=document.createElement('nav');n.className='indo-global-bottom-nav';n.setAttribute('aria-label','Primary navigation');n.innerHTML=`<button type="button" data-screen="home" class="${a==='home'?'active':''}"><span class="indo-nav-icon">⌂</span><span>Home</span></button><button type="button" data-screen="messages" class="${a==='messages'?'active':''}"><span class="indo-nav-icon">⌕</span><span>Message</span></button><button type="button" data-screen="reels" class="${a==='reels'?'active':''}"><span class="indo-nav-icon">▶</span><span>Reel</span></button><button type="button" data-screen="video" class="${a==='video'?'active':''}"><span class="indo-nav-icon">▣</span><span>Video</span></button><button type="button" data-screen="profile" data-own-profile="1" class="${a==='profile'?'active':''}"><span class="indo-nav-icon">●</span><span>Profile</span></button>`;app.appendChild(n);}
async function lazy(app,path,name,args=[]){try{const m=await import(`${path}?v=${VERSION}`);if(typeof m[name]!=='function')throw new Error(`Missing screen renderer: ${name}`);await m[name](app,...args);}catch(e){routeError(app,e);}}
async function homeTopbar(app){if(state.screen!=='home')return;const m=await import('./screens/home-topbar-v230.js?v=230');m.installHomeTopbarStyles();const old=app.querySelector('.topbar');if(old)old.outerHTML=m.renderHomeTopbar();else{const w=document.createElement('div');w.innerHTML=m.renderHomeTopbar();app.prepend(w.firstElementChild);}}
export function preloadAppScreens(){}
export async function render(app){try{switch(state.screen){case'auth-login':return renderLogin(app);case'auth-signup':return renderSignup(app);case'home':await lazy(app,'./screens/home-v2.js','renderHome');await homeTopbar(app);break;case'messages':await lazy(app,'./screens/messages.js','renderMessages');break;case'reels':await lazy(app,'./screens/reels.js','renderReels');break;case'video':await lazy(app,'./screens/video.js','renderVideo');break;case'watch-video':await lazy(app,'./screens/watch-video-v226.js','renderWatchVideo');break;case'create':await lazy(app,'./screens/create.js','renderCreate');break;case'upload-video':await lazy(app,'./screens/upload-video.js','renderUploadVideo');break;case'story-create':await lazy(app,'./screens/story-create.js','renderStoryCreate',[window.__indoStoryDraftFile instanceof File?window.__indoStoryDraftFile:null]);break;case'profile':await lazy(app,'./screens/profile-clean-v245.js','renderProfile',[state.profile]);break;case'edit-profile':await lazy(app,'./screens/edit-profile-v243.js','renderEditProfile',[state.profile]);break;case'settings':await lazy(app,'./screens/settings.js','renderSettings',[state.accountType,state.earning,state.earningSummary]);break;case'search':await lazy(app,'./screens/search-v232.js','renderSearch');break;case'notifications':await lazy(app,'./screens/notifications-v231.js','renderNotifications');break;case'activity':await lazy(app,'./screens/notifications-v231.js','renderNotifications',['activity']);break;case'wallet':await lazy(app,'./screens/wallet.js','renderWallet');break;case'blocked-users':await lazy(app,'./screens/blocked-users.js','renderBlockedUsers');break;default:state.screen='home';await lazy(app,'./screens/home-v2.js','renderHome');await homeTopbar(app);}globalNav(app);installProfileLinkNavigation();}catch(e){routeError(app,e);}}
